name: parallelproj-benchmark

channels:
  - conda-forge

dependencies:
  - parallelproj>=1.5
  - pydantic>=1.10
  - h5py
  - pandas
  - scipy
  - ipython
  - array-api-compat

  # optional for GPU mode
  # - cupy
  # - pytorch
