name: parallelproj-benchmark

channels:
  - conda-forge

dependencies:
  - parallelproj>=1.5
  - h5py
  - pandas
  - scipy
  - ipython
  - array-api-compat
  - seaborn
  - matplotlib

  # optional for GPU mode
  # - cupy
  # - pytorch
